version: "3.8"

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"           # порт на вашей машине (хосте)
    environment:
      POSTGRES_USER: lul
      POSTGRES_PASSWORD: lul
      POSTGRES_DB: main_db
    volumes:
      - pg_data:/var/lib/postgresql/data        # основной том с данными Postgres
      - ./initdb:/docker-entrypoint-initdb.d     # ваш SQL-код для инициализации

volumes:
  pg_data:
    driver: local
